name: CI

on: [push]

env:
  CI: true
  NODE_ENV: test
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: 14

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Node.js dependencies
        if: "steps.yarn-cache.outputs.cache-hit != 'true'"
        run: yarn --frozen-lockfile

      - name: Linting
        run: yarn lint

      - name: Check types
        run: tsc

      - name: Build
        run: yarn build

      - name: Setup for deploy
        if: "startsWith(github.ref, 'refs/tags/v')"
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          npm whoami

      # prerelease versions must have a '-' to be released
      - name: Publish unstable
        if: "startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-')"
        run: lerna run deploy:unstable --stream

      - name: Publish stable
        if: "startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-')"
        run: lerna run deploy:stable --stream
